### ISSUE TITLE
ImportError (No module named 'UserDict') in Python 3

### ISSUE THREAD

**Issue by rjshaver** [vontio/sublime-xml2json#7]
Tried installing xml2json on sublime text 3.  Immediately, I received the error mentioned above.  There is no module UserDict in Sublime Text 3.  I am not sure if there is an easy workaround for this.  Or even if it is a major problem.  I have not tried using the plugin, just noticed the error.
Here is the console listing for the error:
reloading plugin xml2json.ordereddict
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "ordereddict in C:\Users\rjsha\AppData\Roaming\Sublime Text 3\Installed Packages\xml2json.sublime-package", line 23, in <module>
ImportError: No module named 'UserDict'
reloading plugin xml2json.Xml2json
reloading plugin xml2json.xmltodict

It appears that other portions load without the orderredict.py file.  Can you advise?  Running on:
 Windows 10 Version 1703, Build 15063.674
Sublime Text 3.0, Build 3143 64 bit
It looks like this is running a Python 3.3 subset

  I am sorry, but do not have time now to go through the code to find a solution to this error I am getting.  Thanks.

**Comment by SecureCloud-biz** [comment]
same error.. been about a year still no fix.. 👎 
please fix thi error.. this has potential

```
Windows 10 Version 1709, Build 16299.371

startup, version: 3143 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/[User]/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/[User]/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/[User]/AppData/Roaming/Sublime Text 3/Installed Packages
```

```
reloading plugin url-utils.urlutils
reloading plugin xml2json.ordereddict
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "ordereddict in C:\Users\[User]\AppData\Roaming\Sublime Text 3\Installed Packages\xml2json.sublime-package", line 23, in <module>
ImportError: No module named 'UserDict'
reloading plugin xml2json.Xml2json
reloading plugin xml2json.xmltodict
```

**Comment by rjshaver** [comment]
Yes, I got rid of this when I was still using sublime.  No one is working with this project for years.  If you really need this functionality, you can either find another package or try to convert this one to Python 3.  It should not even be allowed in the available packages for Sublime 3.  To convert this one, I think the UserDict can be converted to a collections.MutableMapping or collections.UserDict.  I have not looked at this extesively, but this would be where to look.  Good luck.  I gave up on Sublime some time ago, so I am avoiding this issue.
